# Generated by Django 5.0.6 on 2024-06-02 23:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_notificacion', models.CharField(blank=True, null=True, verbose_name='Titulo')),
                ('mensaje_notificacion', models.TextField(blank=True, null=True, verbose_name='Mensaje')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Sistema')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-timestamp'],
            },
        ),
    ]
