# Generated by Django 5.0.6 on 2024-05-22 20:10

import appLoginRegistro.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appIberiaExplorer', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, null=True)),
                ('apellido_1', models.CharField(max_length=255)),
                ('apellido_2', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=12, null=True)),
                ('direccion', models.CharField(max_length=75, null=True)),
                ('fecha_baja', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('confirmation_token', models.CharField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.ciudad')),
                ('id_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appIberiaExplorer.plan')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'managed': True,
            },
            managers=[
                ('objects', appLoginRegistro.models.CustomUserManager()),
            ],
        ),
    ]
