# Generated by Django 5.0.6 on 2024-06-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLoginRegistro', '0002_alter_usuario_fecha_baja_alter_usuario_id_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='img/profile_pictures/', verbose_name='Foto Perfil'),
        ),
    ]
