# Generated by Django 5.0.6 on 2024-06-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLoginRegistro', '0003_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='img/profile_pictures/default.png', null=True, upload_to='img/profile_pictures/', verbose_name='Foto Perfil'),
        ),
    ]
