# Generated by Django 5.0.3 on 2024-03-28 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoPlan',
            fields=[
                ('id_atributo_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('duracion', models.IntegerField()),
                ('admite_perro', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id_continente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('duracion', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido_1', models.CharField(max_length=255)),
                ('apellido_2', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.BinaryField()),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=75)),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.ciudad')),
                ('id_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appIberiaExplorer.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_continente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.continente'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('texto_notificacion', models.CharField(max_length=255)),
                ('hora_notificacion', models.DateTimeField()),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('id_continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.continente')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.pais'),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id_favorito', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.plan')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id_estado_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('detalles', models.CharField(max_length=255)),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=255)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.ciudad')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.pais')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.proveedor'),
        ),
        migrations.CreateModel(
            name='TipoPlan',
            fields=[
                ('id_tipo_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_plan', models.CharField(max_length=255)),
                ('id_atributo_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.atributoplan')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_estado_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.estadoreserva')),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.plan')),
                ('id_tipo_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.tipoplan')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='id_tipo_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.tipoplan'),
        ),
        migrations.CreateModel(
            name='UsuarioPreferencia',
            fields=[
                ('id_preferencia', models.AutoField(primary_key=True, serialize=False)),
                ('id_atributo_plan_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.atributoplan')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
