# Generated by Django 5.0.6 on 2024-05-22 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appIberiaExplorer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_continente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.continente'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pais',
            name='id_continente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.continente'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.pais'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='id_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.plan'),
        ),
        migrations.AddField(
            model_name='estadoreserva',
            name='id_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.plan'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.plan'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.ciudad'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.pais'),
        ),
        migrations.AddField(
            model_name='plan',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.proveedor'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_estado_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.estadoreserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.plan'),
        ),
        migrations.AddField(
            model_name='tipoplan',
            name='id_atributo_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.atributoplan'),
        ),
        migrations.AddField(
            model_name='tipoplan',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.proveedor'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_tipo_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.tipoplan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='id_tipo_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.tipoplan'),
        ),
        migrations.AddField(
            model_name='usuariopreferencia',
            name='id_atributo_plan_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.atributoplan'),
        ),
        migrations.AddField(
            model_name='usuariopreferencia',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
