# Generated by Django 5.0.3 on 2024-03-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_baja',
            field=models.DateTimeField(null=True),
        ),
    ]
