# Generated by Django 5.0.6 on 2024-05-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0003_carrito_carritodetalle_pedido_pedidodetalle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='id_proveedor',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='id_tipo_plan',
        ),
    ]
