# Generated by Django 5.0.6 on 2024-05-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0005_alter_carrito_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
