# Generated by Django 5.0.6 on 2024-05-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0006_alter_pedido_fecha_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritodetalle',
            name='id_carrito',
        ),
        migrations.RemoveField(
            model_name='carritodetalle',
            name='id_plan',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='pedidodetalle',
            name='id_pedido',
        ),
        migrations.RemoveField(
            model_name='pedidodetalle',
            name='id_plan',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='CarritoDetalle',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoDetalle',
        ),
    ]
