# Generated by Django 5.0.3 on 2024-03-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0006_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atributoplan',
            options={'managed': True, 'verbose_name': 'AtributoPlan', 'verbose_name_plural': 'AtributoPlanes'},
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'managed': True, 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'managed': True, 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='continente',
            options={'managed': True, 'verbose_name': 'Continente', 'verbose_name_plural': 'Continentes'},
        ),
        migrations.AlterModelOptions(
            name='estadoreserva',
            options={'managed': True, 'verbose_name': 'EstadoReserva', 'verbose_name_plural': 'EstadoReservas'},
        ),
        migrations.AlterModelOptions(
            name='favorito',
            options={'managed': True, 'verbose_name': 'Favorito', 'verbose_name_plural': 'Favoritos'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'managed': True, 'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'managed': True, 'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'managed': True, 'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': True, 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'managed': True, 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='tipoplan',
            options={'managed': True, 'verbose_name': 'TipoPlan', 'verbose_name_plural': 'TipoPlanes'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True, 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usuariopreferencia',
            options={'managed': True, 'verbose_name': 'UsuarioPreferencia', 'verbose_name_plural': 'UsuarioPreferencias'},
        ),
    ]
