# Generated by Django 5.0.6 on 2024-05-30 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0007_remove_carritodetalle_id_carrito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoplan',
            name='id_proveedor',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='nombre',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='duracion',
        ),
        migrations.AddField(
            model_name='plan',
            name='codigo_postal',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='hora_inicio',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='id_tipo_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.tipoplan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='nombre_calle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='nombre_lugar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='organizador',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='atributoplan',
            name='admite_perro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atributoplan',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='atributoplan',
            name='duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atributoplan',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atributoplan',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atributoplan',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='atributoplan',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
