# Generated by Django 5.0.6 on 2024-05-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0009_remove_plan_id_tipo_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='id_plan_api',
            field=models.IntegerField(null=True),
        ),
    ]
