# Generated by Django 5.0.6 on 2024-06-02 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0010_plan_id_plan_api'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
