# Generated by Django 5.0.6 on 2024-06-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0011_delete_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorito',
            name='id_plan',
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='id_usuario',
        ),
        migrations.DeleteModel(
            name='EstadoReserva',
        ),
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
