# Generated by Django 5.0.6 on 2024-06-13 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0012_remove_favorito_id_plan_remove_favorito_id_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='id_plan',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='id_usuario',
        ),
        migrations.DeleteModel(
            name='TipoPlan',
        ),
        migrations.RemoveField(
            model_name='usuariopreferencia',
            name='id_atributo_plan_plan',
        ),
        migrations.RemoveField(
            model_name='usuariopreferencia',
            name='id_usuario',
        ),
        migrations.RenameField(
            model_name='ciudad',
            old_name='id_pais',
            new_name='pais',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='id_continente',
            new_name='continente',
        ),
        migrations.RemoveField(
            model_name='atributoplan',
            name='admite_perro',
        ),
        migrations.RemoveField(
            model_name='atributoplan',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='atributoplan',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='atributoplan',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='atributoplan',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='atributoplan',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='id_continente',
        ),
        migrations.AddField(
            model_name='atributoplan',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appIberiaExplorer.plan'),
        ),
        migrations.AddField(
            model_name='atributoplan',
            name='url',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id_plan_api',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='UsuarioPreferencia',
        ),
    ]
