# Generated by Django 5.0.3 on 2024-03-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0015_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='confirmation_token',
            field=models.CharField(default='7jHyUPMdUqhjJ7Z1EgYpykrv2zZOKDRji211Q5wGKkDIlDUUS2', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
