# Generated by Django 5.0.3 on 2024-03-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0016_usuario_confirmation_token_usuario_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='confirmation_token',
            field=models.CharField(default='7enJhlibWuHRLXzndcYrYsYECk4AbkDEwY2OqbS7WdrsmvsCiS', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
