# Generated by Django 5.0.3 on 2024-03-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0017_alter_usuario_confirmation_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='confirmation_token',
            field=models.CharField(default='NvMrbIySwc7ZLuiKqUe6w83hxzEVsuyE9QrFVL2YpnTe0dZbXZ', max_length=50),
        ),
    ]
