# Generated by Django 5.0.3 on 2024-03-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0018_alter_usuario_confirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='confirmation_token',
            field=models.CharField(default='gacbRc31Fkr6sRPAqUyaSdfg4DIaY5wFmkM6ipZoCAM7vMqhjE', max_length=50),
        ),
    ]
