# Generated by Django 5.0.3 on 2024-03-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0019_alter_usuario_confirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='confirmation_token',
            field=models.CharField(default='rECXiCBFysJc0eQMmrwidJJmsxJcS91qpOTwD165VAtrkO9N5U', max_length=50),
        ),
    ]
