# Generated by Django 5.0.3 on 2024-03-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0021_alter_usuario_confirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='confirmation_token',
            field=models.CharField(default='gzSyHtn48oqLmA84XakzPT32FYU1IHaB0o38uQrJDpek0NrJ4T', max_length=50),
        ),
    ]
