# Generated by Django 5.0.3 on 2024-03-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0022_alter_usuario_confirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='confirmation_token',
            field=models.CharField(default='PgYRU73WJAtd7Th7KtTVMFXmZyJkRUy2A5koVMiwojr0GiRQC7', max_length=50),
        ),
    ]
