# Generated by Django 5.0.3 on 2024-03-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0023_alter_usuario_confirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='confirmation_token',
            field=models.CharField(default='HwEC5zpnGR6kvN9JetEYuI4Wy98drTKTZ5yP57yYGPVlxbAsVl', max_length=50),
        ),
    ]
