# Generated by Django 5.0.3 on 2024-03-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0024_alter_usuario_confirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='confirmation_token',
            field=models.CharField(default='q4qsVu49A2GRzdRUk9spTpF7R4zqgvNYpXLYYcu5E1D4MKmzf5', max_length=50),
        ),
    ]
