# Generated by Django 5.0.3 on 2024-03-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0026_alter_usuario_confirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='confirmation_token',
            field=models.CharField(default='VaHb3YhOoBLuZLhVBrynKfh3vgzKdzfOnOnwG93rtxkfOEVlVi', max_length=50),
        ),
    ]
