# Generated by Django 5.0.3 on 2024-03-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0027_alter_usuario_confirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='confirmation_token',
            field=models.CharField(default='8Vn6Ltm8bfEYnqJu3cbItY0u1LwrbicbA4q9aHX6fXp072TgOG', max_length=50),
        ),
    ]
