# Generated by Django 5.0.3 on 2024-03-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0029_alter_usuario_confirmation_token_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='confirmation_token',
            field=models.CharField(default='U09i9tiCmcuSDF6TdEgN6sdwV1cJCKhQc8WuyQtkD4N9HPayJP', max_length=50),
        ),
    ]
