# Generated by Django 5.0.3 on 2024-03-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIberiaExplorer', '0030_alter_usuario_confirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='confirmation_token',
            field=models.CharField(default='sqixYdfjS6pEY8EeHGZOTYv5iz5tDp38OlMrEGyDjAqhsJSND9', max_length=50),
        ),
    ]
