# Generated by Django 5.0.6 on 2024-05-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCarritoPedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritodetalle',
            name='coste_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
